// Generated by CoffeeScript 1.12.7
(function() {
  var http, server;

  http = require('http');

  server = require('./app.js');

  http.createServer(server.logic).listen(server.port, server.address);
 console.log("access by navigating to " + server.address +":"+server.port);
}).call(this);
