// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    save: function(user, password, callback) {
      if (callback === null) {
        new Error('missing parameters');
      } else {
        console.log('function save called with user : ' + user);
        callback();
      }
    },
    get: function(id, callback) {
      if (callback === null) {
        new Error('missing parameters');
      } else {
        console.log('getting user with id : ' + id);
        callback();
      }
    }
  };

}).call(this);
